package gui;

import java.applet.AudioClip;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * @author jose
 */
public class Ahorcado extends javax.swing.JFrame {

    //declarar variables - alternar sonido
    AudioClip sound;
    boolean isPlaying;
    boolean isMute;

    //declarar variables - estado del juego
    int puntaje = 0;
    int intentos = 1;
    int intentosMaximos = 10;
    boolean enJuego = true;

    //declarar variables - palabra oculta
    String palabraOculta;
    String letrasAgregadas;
    char[] letrasAdivinadas;

    public Ahorcado() {
        initComponents();
         setIconImage(new ImageIcon(getClass().getResource("/images/icon.png")).getImage());
        darInicio();

        sound = java.applet.Applet.newAudioClip(getClass().getResource("/sounds/juego.wav"));

        sound.loop();

        isPlaying = true;
        isMute = false;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLetra = new javax.swing.JTextField();
        lblLetras = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblPuntaje = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ahorcado: Adivina o Pierdes");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("¿Qué letra falta? Intenta adivinarla");

        txtLetra.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        txtLetra.setToolTipText("");

        lblLetras.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lblLetras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLetras.setText("------");

        btnSiguiente.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bengala.png"))); // NOI18N
        btnSiguiente.setText("  Adivinar");
        btnSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnReiniciar.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnReiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/siguiente.png"))); // NOI18N
        btnReiniciar.setText("  Nuevo Juego");
        btnReiniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ahorcado.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Record:");

        lblPuntaje.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        lblPuntaje.setForeground(new java.awt.Color(0, 0, 204));
        lblPuntaje.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(30, 30, 30)
                .addComponent(lblPuntaje)
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                    .addComponent(lblLetras, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblPuntaje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLetras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jMenuBar1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N

        jMenu1.setText("Inicio");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu1MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sonido");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu2MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed

        // Leer la letra ingresada por el usuario y convertirla a minúscula
        String letraIngresada = txtLetra.getText().toLowerCase();

        // Verificar si se ingresó solo una letra
        if (letraIngresada.length() == 1) {

            boolean letraCorrecta = false;

            // Iterar a través de la palabra oculta para buscar la letra ingresada
            for (int i = 0; i < palabraOculta.length(); i++) {
                // Si la letra es correcta, se actualiza la letra en la posición correspondiente
                if (Character.toLowerCase(palabraOculta.charAt(i)) == letraIngresada.charAt(0)) {
                    letrasAdivinadas[i] = palabraOculta.charAt(i);
                    letraCorrecta = true;
                }
            }

            // Actualizar el texto en la interfaz con las letras adivinadas hasta el momento
            letrasAgregadas = new String(letrasAdivinadas);
            lblLetras.setText(letrasAgregadas);
            txtLetra.setText("");

            //comprobar si se ganó
            String comprobar = lblLetras.getText();
            if (comprobar.equalsIgnoreCase(palabraOculta)) {

                //llamar metodo de victoria
                ganarPartida();

            }
            // Si la letra es incorrecta, actualizar el número de intentos y mostrar un mensaje
            if (!letraCorrecta && intentos <= 10) {
                JOptionPane.showMessageDialog(null, "Respuesta incorrecta. Te quedan " + (intentosMaximos - intentos) + " intentos",
                        "Intentos Restantes", JOptionPane.WARNING_MESSAGE);
                intentos++;
            }

            // Si se alcanza el número máximo de intentos, finalizar el juego
            if (intentos == (intentosMaximos + 1)) {
                enJuego = false;
            }

            if (enJuego == false) {
                perderPartida();

            }

            // Si el usuario no ingresa una sola letra, mostrar un mensaje de advertencia
        } else if (letraIngresada.length() > 1) {
            JOptionPane.showMessageDialog(rootPane, "Por favor, ingresa solo una letra.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Por favor, ingresa una letra.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        darInicio();

        txtLetra.setText("");
        intentos = 1;
        enJuego = true;

        txtLetra.setEnabled(true);
        btnSiguiente.setEnabled(true);
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void jMenu2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MousePressed

        alternarSonido();

    }//GEN-LAST:event_jMenu2MousePressed

    private void jMenu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MousePressed

        Inicio ventana = new Inicio();
        this.dispose();
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        sound.stop();

    }//GEN-LAST:event_jMenu1MousePressed

    public void darInicio() {
        
        //palabras posibles para el juego
        String palabras[] = {"mesa", "casa", "perro", "zapato", "calle", "sol", "luna", "flor", "ciudad", "escuela", "gente",
            "libro", "silla", "cama", "madre", "puerta", "amigo", "comida", "agua", "lluvia", "pelota", "rojo", "noche", "gato"};

        //sorteo de palabras
        Random palabraRandom = new Random();
        int indice = palabraRandom.nextInt(palabras.length);
        palabraOculta = palabras[indice];

        letrasAdivinadas = new char[palabraOculta.length()];

        for (int i = 0; i < letrasAdivinadas.length; i++) {
            letrasAdivinadas[i] = '-';
        }

        this.letrasAgregadas = new String(letrasAdivinadas);
        lblLetras.setText(letrasAgregadas);

    }

    public void ganarPartida() {

        JOptionPane.showMessageDialog(rootPane, "¡Felicidades, has ganado!", "¡Éxito!", JOptionPane.INFORMATION_MESSAGE);
        txtLetra.setText(" ");
        txtLetra.setEnabled(false);
        puntaje++;
        lblPuntaje.setText("+" + puntaje + "");
        btnSiguiente.setEnabled(false);
    }

    public void perderPartida() {
        JOptionPane.showMessageDialog(null, "¡Lo siento, has perdido! Intenta nuevamente.", "Error", JOptionPane.ERROR_MESSAGE);
        txtLetra.setText("");
        txtLetra.setEnabled(false);
        puntaje = 0;
        lblLetras.setText(":(");
        btnSiguiente.setEnabled(false);
    }

    public void alternarSonido() {

        if (isMute) {
            sound.loop();
            isPlaying = true;
        } else {
            sound.stop();
            isPlaying = false;
        }

        isMute = !isPlaying;

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLetras;
    private javax.swing.JLabel lblPuntaje;
    private javax.swing.JTextField txtLetra;
    // End of variables declaration//GEN-END:variables

}
